package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgerrcode"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/rdaniel1105/go-oidc-provider/internal/domain"
)

// ClientStore persists OAuth/OIDC clients in Postgres. All methods take a
// context and return domain.Client values; pgx errors are wrapped, and the
// unique-violation on a live client_id is mapped to domain.ErrClientIDTaken.
type ClientStore struct {
	pool *pgxpool.Pool
}

// NewClientStore returns a ClientStore backed by the given pool.
func NewClientStore(pool *pgxpool.Pool) *ClientStore {
	return &ClientStore{pool: pool}
}

// Create inserts a new client row. The id is generated by Postgres if Client.ID
// is the zero UUID. Returns ErrClientIDTaken if the client_id collides with an
// existing live row.
func (s *ClientStore) Create(ctx context.Context, c *domain.Client) (*domain.Client, error) {
	const q = `
		INSERT INTO clients (
			client_id, client_secret_hash, redirect_uris, grant_types,
			response_types, scopes, token_endpoint_auth_method,
			client_notification_endpoint, backchannel_token_delivery_mode
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
		RETURNING id, client_id, client_secret_hash, redirect_uris, grant_types,
		          response_types, scopes, token_endpoint_auth_method,
		          client_notification_endpoint, backchannel_token_delivery_mode,
		          created_at, updated_at
	`

	row := s.pool.QueryRow(ctx, q,
		c.ClientID,
		c.ClientSecretHash,
		c.RedirectURIs,
		c.GrantTypes,
		c.ResponseTypes,
		c.Scopes,
		string(c.TokenEndpointAuthMethod),
		c.ClientNotificationEndpoint,
		ptrString(c.BackchannelTokenDeliveryMode),
	)

	got, err := scanClient(row)
	if err == nil {
		return got, nil
	}

	if pgErr, ok := errors.AsType[*pgconn.PgError](err); ok && pgErr.Code == pgerrcode.UniqueViolation {
		return nil, domain.ErrClientIDTaken
	}

	return nil, err
}

// GetByClientID returns the live client with the given client_id, or
// ErrClientNotFound if no live row matches.
func (s *ClientStore) GetByClientID(ctx context.Context, clientID string) (*domain.Client, error) {
	const q = `
		SELECT id, client_id, client_secret_hash, redirect_uris, grant_types,
		       response_types, scopes, token_endpoint_auth_method,
		       client_notification_endpoint, backchannel_token_delivery_mode,
		       created_at, updated_at
		FROM clients
		WHERE client_id = $1 AND deleted_at IS NULL
	`

	return scanClient(s.pool.QueryRow(ctx, q, clientID))
}

func scanClient(row pgx.Row) (*domain.Client, error) {
	var (
		c       domain.Client
		method  string
		mode    *string
	)

	err := row.Scan(
		&c.ID,
		&c.ClientID,
		&c.ClientSecretHash,
		&c.RedirectURIs,
		&c.GrantTypes,
		&c.ResponseTypes,
		&c.Scopes,
		&method,
		&c.ClientNotificationEndpoint,
		&mode,
		&c.CreatedAt,
		&c.UpdatedAt,
	)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, domain.ErrClientNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("scan client: %w", err)
	}

	c.TokenEndpointAuthMethod = domain.TokenEndpointAuthMethod(method)
	if mode != nil {
		m := domain.CIBADeliveryMode(*mode)
		c.BackchannelTokenDeliveryMode = &m
	}

	return &c, nil
}

func ptrString[T ~string](p *T) *string {
	if p == nil {
		return nil
	}
	s := string(*p)
	return &s
}
