package postgres

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgerrcode"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/rdaniel1105/go-oidc-provider/internal/domain"
)

// RefreshTokenStore persists refresh-token records. Lookups are by hash
// (the same hash held in the row) and never by the raw bearer string —
// raw tokens are not stored. The store does not interpret expiry or
// revocation; it returns rows verbatim and lets the calling service
// decide what to do with revoked or expired state.
type RefreshTokenStore struct {
	pool *pgxpool.Pool
}

// NewRefreshTokenStore returns a RefreshTokenStore backed by the given pool.
func NewRefreshTokenStore(pool *pgxpool.Pool) *RefreshTokenStore {
	return &RefreshTokenStore{pool: pool}
}

// Create inserts a new refresh-token row. The id is generated by Postgres
// if RefreshToken.ID is the zero UUID; FamilyID defaults to a fresh
// uuid.New() when the caller leaves it zero (i.e. this is the first
// token in a new chain), and AuthTime defaults to the current time —
// the rotation path passes both explicitly so every refreshed token
// inherits the chain's identity. Returns ErrRefreshTokenHashTaken when
// the token_hash uniqueness constraint fires.
func (s *RefreshTokenStore) Create(ctx context.Context, t *domain.RefreshToken) (*domain.RefreshToken, error) {
	if t.FamilyID == uuid.Nil {
		t.FamilyID = uuid.New()
	}

	if t.AuthTime.IsZero() {
		t.AuthTime = time.Now().UTC()
	}

	const q = `
		INSERT INTO refresh_tokens (token_hash, client_id, op_user_id, family_id, scope, auth_time, expires_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id, token_hash, client_id, op_user_id, family_id, scope, auth_time, issued_at, expires_at, revoked_at
	`

	row := s.pool.QueryRow(ctx, q,
		t.TokenHash,
		t.ClientID,
		t.OPUserID,
		t.FamilyID,
		t.Scope,
		t.AuthTime,
		t.ExpiresAt,
	)

	got, err := scanRefreshToken(row)
	if err == nil {
		return got, nil
	}

	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == pgerrcode.UniqueViolation {
		return nil, domain.ErrRefreshTokenHashTaken
	}

	return nil, err
}

// GetByHash returns the refresh-token row with the given token_hash, or
// ErrRefreshTokenNotFound. The row is returned regardless of revoked_at
// or expires_at — the rotation flow needs to see revoked rows to detect
// theft.
func (s *RefreshTokenStore) GetByHash(ctx context.Context, hash string) (*domain.RefreshToken, error) {
	const q = `
		SELECT id, token_hash, client_id, op_user_id, family_id, scope, auth_time, issued_at, expires_at, revoked_at
		FROM refresh_tokens
		WHERE token_hash = $1
	`

	return scanRefreshToken(s.pool.QueryRow(ctx, q, hash))
}

// Revoke stamps revoked_at on the row with the given id. A no-op (no
// error) if the row is already revoked; the revoked_at timestamp is not
// overwritten in that case so the original revocation moment is preserved.
func (s *RefreshTokenStore) Revoke(ctx context.Context, id uuid.UUID, at time.Time) error {
	const q = `
		UPDATE refresh_tokens
		SET revoked_at = $2
		WHERE id = $1 AND revoked_at IS NULL
	`

	tag, err := s.pool.Exec(ctx, q, id, at)
	if err != nil {
		return fmt.Errorf("revoke refresh token: %w", err)
	}

	if tag.RowsAffected() == 0 {
		if _, getErr := s.getByID(ctx, id); getErr != nil {
			return getErr
		}
		// Row exists and was already revoked — no-op.
	}

	return nil
}

// RevokeAllForUser stamps revoked_at on every live refresh token issued
// to the given op_user. Useful for "log out everywhere" actions; the
// rotation flow uses RevokeFamily instead to limit blast radius.
func (s *RefreshTokenStore) RevokeAllForUser(ctx context.Context, opUserID uuid.UUID, at time.Time) (int64, error) {
	const q = `
		UPDATE refresh_tokens
		SET revoked_at = $2
		WHERE op_user_id = $1 AND revoked_at IS NULL
	`

	tag, err := s.pool.Exec(ctx, q, opUserID, at)
	if err != nil {
		return 0, fmt.Errorf("revoke refresh tokens for user: %w", err)
	}

	return tag.RowsAffected(), nil
}

// RevokeFamily stamps revoked_at on every live refresh token sharing
// the given family_id. Called when a replay of an already-revoked token
// is detected: the attacker holds some descendant of this family, so
// every live descendant — including the one the legitimate user holds
// — is revoked to force a fresh authentication.
func (s *RefreshTokenStore) RevokeFamily(ctx context.Context, familyID uuid.UUID, at time.Time) (int64, error) {
	const q = `
		UPDATE refresh_tokens
		SET revoked_at = $2
		WHERE family_id = $1 AND revoked_at IS NULL
	`

	tag, err := s.pool.Exec(ctx, q, familyID, at)
	if err != nil {
		return 0, fmt.Errorf("revoke refresh token family: %w", err)
	}

	return tag.RowsAffected(), nil
}

func (s *RefreshTokenStore) getByID(ctx context.Context, id uuid.UUID) (*domain.RefreshToken, error) {
	const q = `
		SELECT id, token_hash, client_id, op_user_id, family_id, scope, auth_time, issued_at, expires_at, revoked_at
		FROM refresh_tokens
		WHERE id = $1
	`

	return scanRefreshToken(s.pool.QueryRow(ctx, q, id))
}

func scanRefreshToken(row pgx.Row) (*domain.RefreshToken, error) {
	var t domain.RefreshToken

	err := row.Scan(
		&t.ID,
		&t.TokenHash,
		&t.ClientID,
		&t.OPUserID,
		&t.FamilyID,
		&t.Scope,
		&t.AuthTime,
		&t.IssuedAt,
		&t.ExpiresAt,
		&t.RevokedAt,
	)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, domain.ErrRefreshTokenNotFound
	}

	if err != nil {
		return nil, fmt.Errorf("scan refresh_token: %w", err)
	}

	return &t, nil
}
