package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgerrcode"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/rdaniel1105/go-oidc-provider/internal/domain"
)

// OPUserStore persists op_user rows in Postgres. Unique-violation errors
// are mapped to specific sentinels (ErrEmailTaken, ErrPhoneTaken,
// ErrPasskeyUserIDTaken) by inspecting the constraint name; this keeps
// signup error messaging precise instead of collapsing to a generic
// "conflict" response.
type OPUserStore struct {
	pool *pgxpool.Pool
}

// NewOPUserStore returns an OPUserStore backed by the given pool.
func NewOPUserStore(pool *pgxpool.Pool) *OPUserStore {
	return &OPUserStore{pool: pool}
}

// Create inserts a new op_user. The id is generated by Postgres if
// OPUser.ID is the zero UUID. Returns the matching ErrEmailTaken /
// ErrPhoneTaken / ErrPasskeyUserIDTaken when the corresponding partial
// unique index fires.
func (s *OPUserStore) Create(ctx context.Context, u *domain.OPUser) (*domain.OPUser, error) {
	const q = `
		INSERT INTO op_users (email, display_name, phone_e164, passkey_user_id)
		VALUES ($1, $2, $3, $4)
		RETURNING id, email, display_name, phone_e164, passkey_user_id, created_at
	`

	row := s.pool.QueryRow(ctx, q, u.Email, u.DisplayName, u.PhoneE164, u.PasskeyUserID)

	got, err := scanOPUser(row)
	if err == nil {
		return got, nil
	}

	if pgErr, ok := errors.AsType[*pgconn.PgError](err); ok && pgErr.Code == pgerrcode.UniqueViolation {
		switch pgErr.ConstraintName {
		case "op_users_email_unique_live":
			return nil, domain.ErrEmailTaken
		case "op_users_phone_e164_unique_live":
			return nil, domain.ErrPhoneTaken
		case "op_users_passkey_user_id_unique_live":
			return nil, domain.ErrPasskeyUserIDTaken
		}
	}

	return nil, err
}

// GetByID returns the op_user with the given id or ErrOPUserNotFound.
func (s *OPUserStore) GetByID(ctx context.Context, id uuid.UUID) (*domain.OPUser, error) {
	const q = `
		SELECT id, email, display_name, phone_e164, passkey_user_id, created_at
		FROM op_users
		WHERE id = $1 AND deleted_at IS NULL
	`

	return scanOPUser(s.pool.QueryRow(ctx, q, id))
}

// GetByEmail returns the op_user with the given email or ErrOPUserNotFound.
// Used to resolve the CIBA login_hint into an op_user_id.
func (s *OPUserStore) GetByEmail(ctx context.Context, email string) (*domain.OPUser, error) {
	const q = `
		SELECT id, email, display_name, phone_e164, passkey_user_id, created_at
		FROM op_users
		WHERE email = $1 AND deleted_at IS NULL
	`

	return scanOPUser(s.pool.QueryRow(ctx, q, email))
}

// GetByPasskeyUserID returns the op_user linked to the given passkey
// service user, or ErrOPUserNotFound. Used during the CIBA approval flow
// to verify that the asserted passkey belongs to the user the original
// /bc-authorize call resolved.
func (s *OPUserStore) GetByPasskeyUserID(ctx context.Context, passkeyUserID uuid.UUID) (*domain.OPUser, error) {
	const q = `
		SELECT id, email, display_name, phone_e164, passkey_user_id, created_at
		FROM op_users
		WHERE passkey_user_id = $1 AND deleted_at IS NULL
	`

	return scanOPUser(s.pool.QueryRow(ctx, q, passkeyUserID))
}

func scanOPUser(row pgx.Row) (*domain.OPUser, error) {
	var u domain.OPUser

	err := row.Scan(&u.ID, &u.Email, &u.DisplayName, &u.PhoneE164, &u.PasskeyUserID, &u.CreatedAt)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, domain.ErrOPUserNotFound
	}

	if err != nil {
		return nil, fmt.Errorf("scan op_user: %w", err)
	}

	return &u, nil
}
